# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculating penalty matrix
#' 
#' This function calculates the penalty matrix for a given number of 
#' parameters (`nparams`) and a given number of differences (`differences`).
#' 
#' @param nparams [\code{integer(1)}]\cr 
#'   Number of params which should be penalized.
#'   This also pretend the number of rows and columns.
#' @param differences [\code{integer(1)}]\cr 
#'   Number of penalized differences.//' 
#' @return \code{arma::sp_mat} Sparse penalty matrix used for p splines. 
#' @examples
#' pen = penaltyMat(10, 2)
#' @export
penaltyMat <- function(nparams, differences) {
    .Call(`_compboostSplines_penaltyMat`, nparams, differences)
}

#' Binary search to find index of given point within knots
#' 
#' This small functions search for the position of `x` within the
#' `knots` and returns the smalles index for which x >= knots[i].
#' 
#' Note that this function returns the `C++` index which starts 
#' with `0` and ends with `n-1`.
#'
#' @param x [\code{numeric(1)}]\cr 
#'   Point to search for position in knots.
#' @param knots [\code{numeric}]\cr 
#'   Vector of knots. It's the users responsibility to pass a sorted vector.
#' @return Index of position of \code{x} in `knots`.
#' @examples
#' knots = 1:10
#' findSpan(1, knots)
#' findSpan(2.5, knots)
#' findSpan(9.5, knots)
#' findSpan(10, knots)
#' @export
findSpan <- function(x, knots) {
    .Call(`_compboostSplines_findSpan`, x, knots)
}

#' Create knots for a specific number, degree and values
#' 
#' This functions takes a vector of points and creates knots used for the
#' splines depending on the number of knots and degree. This function just
#' handles equidistant knots.
#' 
#' @param values [\code{numeric}]\cr 
#'   Points to create the basis matrix.
#' @param n_knots [\code{integer(1)}]\cr 
#'   Number of innter knots.
#' @param degree [\code{integer(1)]}\cr 
#'   Polynomial degree of splines.
#' @return Vector of knots.
#' @examples
#' x = sort(runif(100, 0, 10))
#' y = 2 * sin(x) + rnorm(100, 0, 0.5)
#' 
#' # Create knots on the space of x:
#' knots = createKnots(values = x, n_knots = 7, degree = 3)
#' @export
createKnots <- function(values, n_knots, degree) {
    .Call(`_compboostSplines_createKnots`, values, n_knots, degree)
}

#' Transformation from a vector of input points to dense matrix of basis
#' 
#' This functions takes a vector of points and create a sparse matrix of
#' basis functions. Each row contains the basis of the corresponding value 
#' in `values`.
#' 
#' @param values [\code{numeric}]\cr 
#'   Points to create the basis matrix.
#' @param degree [\code{integer(1)}]\cr 
#'   Polynomial degree of splines.
#' @param knots [\code{numeric}]\cr 
#'   Vector of knots on which the splines are computed.
#' @return Vector of knots.
#' @examples
#' nsim = 100
#' x = sort(runif(nsim, 0, 10))
#' y = 2 * sin(x) + rnorm(nsim, 0, 0.5) 
#' knots = createKnots(values = x, n_knots = 20, degree = 3)
#'
#' # Create spline basis:
#' basis = createSplineBasis(values = x, degree = 3, knots = knots)
#' @export
createSplineBasis <- function(values, degree, knots) {
    .Call(`_compboostSplines_createSplineBasis`, values, degree, knots)
}

#' Transformation from a vector of input points to sparse matrix of basis
#' 
#' This functions takes a vector of points and create a sparse matrix of
#' basis functions. Each row contains the basis of the corresponding value 
#' in `values`.
#' 
#' @param values [\code{numeric}]\cr 
#'   Points to create the basis matrix.
#' @param degree [\code{integer(1)}]\cr 
#'   Polynomial degree of splines.
#' @param knots [\code{numeric}]\cr 
#'   Vector of knots on which the splines are computed.
#' @return Vector of knots.
#' @examples
#' nsim = 100
#' x = sort(runif(nsim, 0, 10))
#' y = 2 * sin(x) + rnorm(nsim, 0, 0.5) 
#' knots = createKnots(values = x, n_knots = 20, degree = 3)
#'
#' # Create spline basis:
#' basis = createSparseSplineBasis(values = x, degree = 3, knots = knots)
#' @export
createSparseSplineBasis <- function(values, degree, knots) {
    .Call(`_compboostSplines_createSparseSplineBasis`, values, degree, knots)
}

